Repository mike-north/ember-api-actions, pull requests merged in 2021-05, with the labels that each got.

#525 chore(CI): Pin `fs-extra` to v9.x to fix "floating dependencies" jobs
  package.json
  yarn.lock
Labels: internal

#524 chore(TravisCI): Remove testing jobs
  .travis.yml
Labels: internal

#528 refactor: use `async/await` in `ember-try` config file
  config/ember-try.js
Labels: internal

#527 chore: Use HTTPS links in `package.json`
  package.json
Labels: documentation

#529 chore: Sort `package.json` file
  package.json
Labels: internal

#530 chore: Delete obsolete JSHint/JSCS config files
  .jscsrc
  .jshintrc
  tests/.jshintrc
Labels: internal

#445 chore: Drop support for Ember v3.19 and below
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#531 chore(renovate): Enable dependency dashboard
  renovate.json
Labels: internal

#533 chore: Remove TravisCI config
  .travis.yml
Labels: internal

#543 Replace `ember-cli-template-lint` with `ember-template-lint`
  package.json
  yarn.lock
Labels: internal

#544 Drop support for Node.js v10 and below
  package.json
  yarn.lock
Labels: breaking
